### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by kiralee**
Fix require php version for php 7.3 and php 7.4

### CODE REVIEW

**Comment by kiralee** [comment]
Hi @pavelleonidov . Please check this pull request.

**Comment by pavelleonidov** [comment]
Could actually have been ~7.3|~7.4 as well, but I'm fine with that. :) Thanks!

**Comment by kiralee** [comment]
Hi @pavelleonidov . Did you update the change to your packagist ?. I still see error.

**Comment by pavelleonidov** [comment]
Did it just now. :)

**Comment by kiralee** [comment]
Nice. Now package are installing awesome!!!!. Please put closed for issue open about "Error  PHP incompatible".

**Pull request merged**
